service: ai-tourism-poc

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    GOOGLE_GEMINI_API_KEY: ${env:GOOGLE_GEMINI_API_KEY}
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}
    PROJECT_NAME: ai-tourism-poc
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-*"
        - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-*/index/*"
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      Resource:
        - "arn:aws:s3:::${self:service}-images-${self:provider.stage}/*"
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::${self:service}-images-${self:provider.stage}"

functions:
  auth:
    handler: functions/auth/handler.main
    events:
      - http:
          path: auth/{proxy+}
          method: ANY
          cors: true

  imageAnalysis:
    handler: functions/image-analysis/handler_gemini.main
    timeout: 15
    memorySize: 512
    reservedConcurrency: 5
    events:
      - http:
          path: analyze
          method: POST
          cors: true

  payment:
    handler: functions/payment/handler.main
    events:
      - http:
          path: payment/{proxy+}
          method: ANY
          cors: true

  userManagement:
    handler: functions/user-management/handler.main
    events:
      - http:
          path: users/{proxy+}
          method: ANY
          cors: true

  imageUpload:
    handler: functions/image-upload/handler.main
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: upload-image
          method: POST
          cors: true

# Resources commented out to avoid conflicts with existing infrastructure
# resources:
#   Resources:


# plugins:
#   - serverless-python-requirements

# custom:
#   pythonRequirements:
#     pipCmdExtraArgs:
#       - --python=/Library/Frameworks/Python.framework/Versions/3.13/bin/python3
#     zip: true
#     slim: true